#!/usr/bin/env node
var http = require('http');
var express = require('express');
var control = require("./controller.js");
var app = express();
var bodyParser=require("body-parser");

app.set('port', 3900);

app.use(express.static(__dirname + '/file'));

app.use(bodyParser.urlencoded({extended:false}));
app.use(bodyParser.json());

http.createServer(app).listen(app.get('port'), function(){
    console.log("express已经启动，请在浏览器地址栏输入：http://127.0.0.1:3900/");
});

app.get('/news', control.operNews);
app.get('/addnews',control.addNews);
app.get('/editnews',control.editNews);
app.get('/delnews', control.delNews);
app.get('/selnews',control.selNews);
app.get('/shownews',control.showNews);
